Make fatal errors fatal

diff --git a/overlay/generic/lib/svc/method/mdata-fetch b/overlay/generic/lib/svc/method/mdata-fetch
--- a/overlay/generic/lib/svc/method/mdata-fetch
+++ b/overlay/generic/lib/svc/method/mdata-fetch
@@ -210,13 +210,14 @@ TYPE: ${type}
 EOF
 
   if [[ -n ${type} && ${type} != "tritonnfs" ]]; then
-      # XXX should this be fatal?
-      echo "WARNING: Unsupported volume type: ${type}" >&2
-      continue
+      echo "FATAL: unsupported volume type: ${type}" >&2
+      exit ${smf_exit_err_fatal}
   fi
 
-  # if we don't have interface name, we don't know what files to write out.
+  # if we don't have volume and mountpoint, we can't add vfstab lines
   if [[ -z ${nfsvolume} || -z ${mountpoint} ]]; then
+      echo "FATAL: invalid volume specification" >&2
+      exit ${SMF_EXIT_ERR_FATAL}
       continue
   fi
 
